name: lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Add $HOME/.local/bin to $PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup selene
        run: |
          wget --no-verbose "https://github.com/Kampfkarren/selene/releases/download/$VERSION/selene-$VERSION-linux.zip"
          echo "$SHA256_CHECKSUM  selene-$VERSION-linux.zip" > "selene-$VERSION-linux.zip.checksum"
          sha256sum --check "selene-$VERSION-linux.zip.checksum"
          unzip "selene-$VERSION-linux.zip"
          install -Dp selene "$HOME/.local/bin/selene"

          echo "::add-matcher::.github/workflows/problem_matchers/selene.json"
        env:
          VERSION: "0.14.0"
          SHA256_CHECKSUM: "6a6a975fa6d503fbf1d46bfb570cc75b2844f6901ad98901961a5d355d472385"

      - name: Install stylua
        run: |
          wget --no-verbose "https://github.com/JohnnyMorganz/StyLua/releases/download/v$VERSION/stylua-$VERSION-linux.zip"
          echo "$SHA256_CHECKSUM  stylua-$VERSION-linux.zip" > "stylua-$VERSION-linux.zip.checksum"
          sha256sum --check "stylua-$VERSION-linux.zip.checksum"
          unzip "stylua-$VERSION-linux.zip"
          install -Dp stylua "$HOME/.local/bin/stylua"
        env:
          VERSION: "0.10.1"
          SHA256_CHECKSUM: "3a2b44de3c0d36b4ef4b617364eced7b560a6b19284f61550e8b679804efd2a3"

      - name: Run selene
        run: selene .

      - name: Run stylua
        run: stylua --check .
